### ISSUE TITLE
Bodymovin on Scroll

### ISSUE THREAD

**Issue by MisterWolf1965** [coolcat-creations/lottie#5]
Hi Elisa,

I implemented your Plugin to display my After Effects Animation in a Joomla Yootheme Pro Template. Would it be possible to start it on scroll?

I have been trying with waypoints without success.

Thanks in advance!

Wolfram

**Comment by coolcat-creations** [comment]
Hi Wolfram, yes it's possible, I have a seperate Lottie code to achieve that.  I sent it to Guido :)

**Comment by MisterWolf1965** [comment]
Great, Thanks!

Mit freundlichen Grüßen

Wolfram Brandhoff
Web-Design

[cid:image001.jpg@01D6A702.0BAB09A0]

Kunze Medien AG
Leopoldstraße 250
80807 München
Telefon (089) 3 81 87 - 184
Telefax (089) 38187 200184
www.kunze-medien.de
<http://www.kunze-medien.de>wolfram.brandhoff@kunze-medien.de
<mailto:%20wolfram.brandhoff@kunze-medien.de>
Sitz und Registergericht München, HRB 134681
Vorstand: Norbert Rubner
Vorsitzender des Aufsichtsrats: RA Bernd Flossmann

[Facebook]<https://www.facebook.com/kunzemedien>  [Google Maps]   [Youtube Channel] <https://www.youtube.com/channel/UCkQlO_GUnRBRKEj5UoG82Lg>
Von: Elisa Foltyn <notifications@github.com>
Gesendet: Dienstag, 20. Oktober 2020 16:55
An: coolcat-creations/lottie <lottie@noreply.github.com>
Cc: Brandhoff Wolfram <Wolfram.Brandhoff@kunze-medien.de>; Author <author@noreply.github.com>
Betreff: Re: [coolcat-creations/lottie] Bodymovin on Scroll (#5)


Hi Wolfram, yes it's possible, I have a seperate Lottie code to achieve that. I sent it to Guido :)
